name: Build and deploy a container to an Azure Web App

env:
  AZURE_WEBAPP_NAME: calculator  # Nom de ton Web App Azure

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: calculator25.azurecr.io
          username: calculator25
          password: 0tUUkBWukQlWxI+wGx4rvgZt0Wkhxt3RMk9iiTgGDe+ACRCBK6oE

      - name: Build and push container image to registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: calculator25.azurecr.io/calculator:latest
          file: ./Dockerfile
          cache-from: type=registry,ref=calculator25.azurecr.io/calculator:latest
          cache-to: type=inline
