name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Récupération du dépôt
    - name: Checkout repository
      uses: actions/checkout@v4

    # Étape 2 : Configuration de Python
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    # Étape 3 : Initialisation de l'environnement
    - name: Initialize environment
      run: make init

    # Étape 4 : Installation des dépendances
    - name: Install dependencies
      run: make install

    # Étape 5 : Exécution des tests
    - name: Run tests
      run: make test

    # Étape 6 : Nettoyage des fichiers temporaires
    - name: Clean up temporary files
      run: make clean

    # Étape 7 : Construction de l'image Docker
    # - name: Build Docker image
    #   run: make docker-build

    # Étape 8 : Exécution de l'application dans Docker
    # - name: Run Docker container
    #   run: make docker-run

    # Étape 9 : Exécution des tests dans Docker
    # - name: Run tests in Docker
    #   run: make docker-test

    # Étape 10 : Vérification supplémentaire (distcheck)
    # - name: Run distcheck
    #   run: make distcheck

    # Étape 11 : Affichage des commandes disponibles
    - name: Display available commands
      run: make help
